### ISSUE TITLE
FitEverything example error

### ISSUE THREAD

**Issue by timscorbett** [MatthewReid854/reliability#44] opened 2023-10-10 18:02 UTC
Is this a known error? Is there a known resolution?

https://reliability.readthedocs.io/en/latest/API/Fitters/Fit_Everything.html

Traceback (most recent call last):
  File "C:\fitters.py", line 15, in <module>
    output = Fit_Everything(logt)
  File "C:\.conda\envs\battery\lib\site-packages\reliability\Fitters.py", line 1263, in __init__
    Fit_Everything.__probability_plot(self)
  File "C:\.conda\envs\battery\lib\site-packages\reliability\Fitters.py", line 1755, in __probability_plot
    Weibull_probability_plot(
  File "C:\.conda\envs\battery\lib\site-packages\reliability\Probability_plotting.py", line 373, in Weibull_probability_plot
    plt.grid(b=True, which="major", color="k", alpha=0.3, linestyle="-")
  File "C:\.conda\envs\battery\lib\site-packages\matplotlib\pyplot.py", line 3144, in grid
    gca().grid(visible=visible, which=which, axis=axis, **kwargs)
  File "C:\.conda\envs\battery\lib\site-packages\matplotlib\axes\_base.py", line 3196, in grid
    self.xaxis.grid(visible, which=which, **kwargs)
  File "C:\.conda\envs\battery\lib\site-packages\matplotlib\axis.py", line 1697, in grid
    self.set_tick_params(which='major', **gridkw)
  File "C:\.conda\envs\battery\lib\site-packages\matplotlib\axis.py", line 958, in set_tick_params
    kwtrans = self._translate_tick_params(kwargs)
  File "C:\.conda\envs\battery\lib\site-packages\matplotlib\axis.py", line 1102, in _translate_tick_params
    raise ValueError(
ValueError: keyword grid_b is not recognized; valid keywords are ['size', 'width', 'color', 'tickdir', 'pad', 'labelsize', 'labelcolor', 'labelfontfamily', 'zorder', 'gridOn', 'tick1On', 'tick2On', 'label1On', 'label2On', 'length', 'direction', 'left', 'bottom', 'right', 'top', 'labelleft', 'labelbottom', 'labelright', 'labeltop', 'labelrotation', 'grid_agg_filter', 'grid_alpha', 'grid_animated', 'grid_antialiased', 'grid_clip_box', 'grid_clip_on', 'grid_clip_path', 'grid_color', 'grid_dash_capstyle', 'grid_dash_joinstyle', 'grid_dashes', 'grid_data', 'grid_drawstyle', 'grid_figure', 'grid_fillstyle', 'grid_gapcolor', 'grid_gid', 'grid_in_layout', 'grid_label', 'grid_linestyle', 'grid_linewidth', 'grid_marker', 'grid_markeredgecolor', 'grid_markeredgewidth', 'grid_markerfacecolor', 'grid_markerfacecoloralt', 'grid_markersize', 'grid_markevery', 'grid_mouseover', 'grid_path_effects', 'grid_picker', 'grid_pickradius', 'grid_rasterized', 'grid_sketch_params', 'grid_snap', 'grid_solid_capstyle', 'grid_solid_joinstyle', 'grid_transform', 'grid_url', 'grid_visible', 'grid_xdata', 'grid_ydata', 'grid_zorder', 'grid_aa', 'grid_c', 'grid_ds', 'grid_ls', 'grid_lw', 'grid_mec', 'grid_mew', 'grid_mfc', 'grid_mfcalt', 'grid_ms']

**Comment by MatthewReid854** [comment] 2023-10-13 08:39
You need to update your version of reliability.
Matplotlib changed the grid_b keyword a long time ago. This has been resolved in reliability. If you update reliability to v0.8.14 and the issue is still occurring then please reopen this issue and provide the code you entered and the output it provided.

**Closed by MatthewReid854** 2023-10-13 08:39 UTC
